# SPDX-FileCopyrightText: 2022-2023 Carnegie Mellon University
# SPDX-License-Identifier: 0BSD

# github_url = "https://github.com/cmusatyalab/wireguard-tools/"

[version]
current = "0.5.0.post.dev0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<extra>\.post\.dev\d+)?
  '''

[[field]]
name = "extra"
default = ""

[git]
message_template = "Bumping to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "src/wireguard_tools/__init__.py"
search = '__version__ = "{current_version}"'

[[before_commit]]
name = "run pre-commit checks and unit test"
cmd = "poetry run poe check"

[[before_commit]]
name = "build sdist and wheels"
cmd = "poetry run poe build"

#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
